name: Deploy API

on:
  schedule:
    - cron: '0 0,12 * * *' # every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instala as dependências
        run: npm install

      - name: Download dos arquivos crús
        run: npm run download

      - name: Converte os arquivos crús para JSON
        run: npm run parse

      - name: Commit & Push das alterações
        uses: actions-js/push@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main


      