name: Deploy API

on:
  schedule:
    - cron: '18 1 * * *' # every day at 01:18 AM
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Instala as dependências
        run: npm install

      - name: Download dos arquivos crús
        run: |
          npm run download
          # npm run download-xml

      - name: Converte os arquivos crús para JSON
        run: |
          npm run parse
          # npm run parse-xml

      - name: Commit & Push das alterações
        uses: actions-js/push@v1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main


