name: Deploy API

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0,12 * * *' # every 12 hours

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Obtém o diretório do cache do NPM
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-20
      
      - name: Instala as dependências
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Download dos arquivos crús
        run: npm run download

      - name: Converte os arquivos crús para JSON
        run: npm run parse

      - name: Commit & Push das alterações
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          message: 'chore: API auto update (${date})'


      